/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        Controler controler = new Controler();
        controler.createAccount();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
