/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        Account accounts = new Account();
        CvsReader cvsBankReader = new CvsReader();// put in argument
        HashMap<String, ArrayList<ArrayList<String>>> allAccount = new HashMap<String, ArrayList<ArrayList<String>>>();
        allAccount = accounts.create(cvsBankReader);
        View view = new View();
        view.displayAccountTransactions(allAccount, "Ben B");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
