/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        Account accounts = new Account();
        CvsReader cvsBankReader = new CvsReader();// put in argument model
        HashMap<String, ArrayList<ArrayList<String>>> allAccounts = new HashMap<String, ArrayList<ArrayList<String>>>();
        allAccounts= accounts.create(cvsBankReader);
        Controler controler= new Controler ();
        View view = new View(controler, allAccounts);

        //view.displayAccountTransactions("Ben B");
        view.displayAll();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
